<?php

namespace ContainerZHx1pCh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X9jceM4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.X9jceM4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.X9jceM4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'provider' => ['privates', '.errored..service_locator.X9jceM4.App\\Entity\\Provider', NULL, 'Cannot autowire service ".service_locator.X9jceM4": it references class "App\\Entity\\Provider" but no such service exists.'],
        ], [
            'provider' => 'App\\Entity\\Provider',
        ]);
    }
}
