<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNNMNWub\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNNMNWub/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNNMNWub.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNNMNWub\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNNMNWub\App_KernelDevDebugContainer([
    'container.build_hash' => 'NNMNWub',
    'container.build_id' => 'de08659b',
    'container.build_time' => 1610169642,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNNMNWub');
